# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm_rsa',
                'doc_host': 'https://risheekkumarb.github.io',
                'git_url': 'https://github.com/risheekkumarb/llm_rsa',
                'lib_path': 'llm_rsa'},
  'syms': { 'llm_rsa.core': { 'llm_rsa.core.RSA': ('core.html#rsa', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSA.__init__': ('core.html#rsa.__init__', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSA.__repr__': ('core.html#rsa.__repr__', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSA._agg_prompt': ('core.html#rsa._agg_prompt', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSA._call_llm': ('core.html#rsa._call_llm', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSA._run_loop': ('core.html#rsa._run_loop', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSA.get_prompts': ('core.html#rsa.get_prompts', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSA.run': ('core.html#rsa.run', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSACandidate': ('core.html#rsacandidate', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSACandidate.__init__': ('core.html#rsacandidate.__init__', 'llm_rsa/core.py'),
                              'llm_rsa.core.RSACandidate.__repr__': ('core.html#rsacandidate.__repr__', 'llm_rsa/core.py')}}}
